/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteRouteImport } from './routes/tasks/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TasksCreateRouteRouteImport } from './routes/tasks/create.route'
import { Route as TasksCreateIndexRouteImport } from './routes/tasks/create.index'
import { Route as TasksIdEditRouteRouteImport } from './routes/tasks/$id.edit.route'
import { Route as TasksIdEditIndexRouteImport } from './routes/tasks/$id.edit.index'

const TasksRouteRoute = TasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRouteRoute,
} as any)
const TasksCreateRouteRoute = TasksCreateRouteRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TasksRouteRoute,
} as any)
const TasksCreateIndexRoute = TasksCreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksCreateRouteRoute,
} as any)
const TasksIdEditRouteRoute = TasksIdEditRouteRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => TasksRouteRoute,
} as any)
const TasksIdEditIndexRoute = TasksIdEditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksIdEditRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks': typeof TasksRouteRouteWithChildren
  '/tasks/create': typeof TasksCreateRouteRouteWithChildren
  '/tasks/': typeof TasksIndexRoute
  '/tasks/$id/edit': typeof TasksIdEditRouteRouteWithChildren
  '/tasks/create/': typeof TasksCreateIndexRoute
  '/tasks/$id/edit/': typeof TasksIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tasks/create': typeof TasksCreateIndexRoute
  '/tasks/$id/edit': typeof TasksIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tasks': typeof TasksRouteRouteWithChildren
  '/tasks/create': typeof TasksCreateRouteRouteWithChildren
  '/tasks/': typeof TasksIndexRoute
  '/tasks/$id/edit': typeof TasksIdEditRouteRouteWithChildren
  '/tasks/create/': typeof TasksCreateIndexRoute
  '/tasks/$id/edit/': typeof TasksIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tasks'
    | '/tasks/create'
    | '/tasks/'
    | '/tasks/$id/edit'
    | '/tasks/create/'
    | '/tasks/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tasks' | '/tasks/create' | '/tasks/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/tasks'
    | '/tasks/create'
    | '/tasks/'
    | '/tasks/$id/edit'
    | '/tasks/create/'
    | '/tasks/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksRouteRoute: typeof TasksRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRouteRoute
    }
    '/tasks/create': {
      id: '/tasks/create'
      path: '/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateRouteRouteImport
      parentRoute: typeof TasksRouteRoute
    }
    '/tasks/create/': {
      id: '/tasks/create/'
      path: '/'
      fullPath: '/tasks/create/'
      preLoaderRoute: typeof TasksCreateIndexRouteImport
      parentRoute: typeof TasksCreateRouteRoute
    }
    '/tasks/$id/edit': {
      id: '/tasks/$id/edit'
      path: '/$id/edit'
      fullPath: '/tasks/$id/edit'
      preLoaderRoute: typeof TasksIdEditRouteRouteImport
      parentRoute: typeof TasksRouteRoute
    }
    '/tasks/$id/edit/': {
      id: '/tasks/$id/edit/'
      path: '/'
      fullPath: '/tasks/$id/edit/'
      preLoaderRoute: typeof TasksIdEditIndexRouteImport
      parentRoute: typeof TasksIdEditRouteRoute
    }
  }
}

interface TasksCreateRouteRouteChildren {
  TasksCreateIndexRoute: typeof TasksCreateIndexRoute
}

const TasksCreateRouteRouteChildren: TasksCreateRouteRouteChildren = {
  TasksCreateIndexRoute: TasksCreateIndexRoute,
}

const TasksCreateRouteRouteWithChildren =
  TasksCreateRouteRoute._addFileChildren(TasksCreateRouteRouteChildren)

interface TasksIdEditRouteRouteChildren {
  TasksIdEditIndexRoute: typeof TasksIdEditIndexRoute
}

const TasksIdEditRouteRouteChildren: TasksIdEditRouteRouteChildren = {
  TasksIdEditIndexRoute: TasksIdEditIndexRoute,
}

const TasksIdEditRouteRouteWithChildren =
  TasksIdEditRouteRoute._addFileChildren(TasksIdEditRouteRouteChildren)

interface TasksRouteRouteChildren {
  TasksCreateRouteRoute: typeof TasksCreateRouteRouteWithChildren
  TasksIndexRoute: typeof TasksIndexRoute
  TasksIdEditRouteRoute: typeof TasksIdEditRouteRouteWithChildren
}

const TasksRouteRouteChildren: TasksRouteRouteChildren = {
  TasksCreateRouteRoute: TasksCreateRouteRouteWithChildren,
  TasksIndexRoute: TasksIndexRoute,
  TasksIdEditRouteRoute: TasksIdEditRouteRouteWithChildren,
}

const TasksRouteRouteWithChildren = TasksRouteRoute._addFileChildren(
  TasksRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksRouteRoute: TasksRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
